site_name: E-commerce Platform Documentation
site_description: Comprehensive documentation for the microservices e-commerce platform

nav:
  - Home: index.md
  - APIs:
    - REST APIs: apis/rest-apis.md
  - Development:
    - Getting Started: development/getting-started.md
    - Testing: development/testing.md

theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - search
  - techdocs-core