# Valores personalizados para Gitea

replicaCount: 1

image:
  pullPolicy: IfNotPresent

service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22

gitea:
  config:
    server:
      DOMAIN: gitea.apps.your-cluster.com
      ROOT_URL: https://gitea.apps.your-cluster.com
      SSH_DOMAIN: gitea.apps.your-cluster.com
    database:
      DB_TYPE: postgres
      HOST: gitea-postgresql:5432
    cache:
      ENABLED: true
      ADAPTER: memory
    webhook:
      ALLOWED_HOST_LIST: "*"

persistence:
  enabled: true
  size: 10Gi

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
  auth:
    database: gitea
    username: gitea

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi