# Valores de producción para Red Hat Developer Hub
helpers:
  operator:
    enabled: true

backstage:
  enabled: true
  replicas: 2
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2000m

route:
  enabled: true
  host: backstage.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
  tls:
    enabled: true