# Valores de producción para Red Hat Developer Hub
helpers:
  operator:
    enabled: true
    operators:
      rhdh-operator:
        enabled: true
        syncwave: 0
        namespace:
          name: openshift-operators
        subscription:
          channel: stable
          operatorName: rhdh-operator
          source: redhat-operators
  statusChecker:
    enabled: true
    statusChecks:
      checks:
        rhdh-operator:
          enabled: true
          type: deployment
          namespace: openshift-operators
          name: rhdh-operator

operator:
  defaultNamespace: "backstage"

global:
  clusterRouterBase: apps.your-cluster.com
  
backstage:
  enabled: true
  
  replicas: 2  # Producción
  
  image:
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2000m

  postgresql:
    enabled: true
    auth:
      database: backstage
      username: backstage
    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ocs-external-storagecluster-ceph-rbd

  plugins:
    - name: kubernetes
      enabled: true
    - name: techdocs
      enabled: true
    - name: catalog
      enabled: true
    - name: scaffolder
      enabled: true

  auth:
    providers:
      - type: oauth2
        providerId: keycloak
        
  cors:
    origin: "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS

  # Configuración específica de producción
  config:
    app:
      title: "Red Hat Developer Hub - DemoJam 2026"
      baseUrl: https://backstage.apps.your-cluster.com
    backend:
      baseUrl: https://backstage.apps.your-cluster.com
      cors:
        origin: https://backstage.apps.your-cluster.com
    techdocs:
      builder: local
      generator:
        runIn: local
      publisher:
        type: local

route:
  enabled: true
  host: backstage.apps.your-cluster.com
  tls:
    enabled: true