site_name: API Gateway Documentation
site_description: Request routing, authentication, and load balancing for microservices

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: indigo

plugins:
  - techdocs-core