apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base: Helm chart de Red Hat Developer Hub
helmCharts:
- name: setup-rh-developer-hub
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "1.0.0"
  releaseName: rhdh
  namespace: backstage

# Customizaciones específicas para RHDH
patches:
- target:
    kind: Deployment
    name: rhdh
  patch: |
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: APP_CONFIG_app_baseUrl
        value: "https://rhdh.apps.cluster-7n8gb.dynamic.redhatworkshops.io"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: AI_ASSISTANT_API_URL
        value: "https://ai-assistant.apps.cluster-7n8gb.dynamic.redhatworkshops.io"

# Recursos adicionales específicos de RHDH
resources:
- rh-developer-hub-plugins-config.yaml
- rh-developer-hub-catalog-locations.yaml
- rh-developer-hub-ai-plugin-config.yaml

# Labels específicos
commonLabels:
  component: rh-developer-hub