replicaCount: 2

# Namespace configuration
namespace: rhbk-operator

# Red Hat build of Keycloak Operator configuration
operator:
  enabled: true
  channel: "stable"
  installPlanApproval: "Automatic"
  
# Keycloak instance configuration  
keycloak:
  adminUser: "admin"
  adminPassword: "rhbk-admin-123"
  
config:
  hostname: "keycloak.apps.cluster.company.com"
  timezone: "America/Lima"
  logLevel: "INFO"
  backstageUrl: "https://backstage.apps.cluster.company.com"
  aiAssistantUrl: "https://ai-assistant.apps.cluster.company.com"

# PostgreSQL Database for Keycloak
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres123"
    username: "keycloak"
    password: "keycloak123"
    database: "keycloak"
  primary:
    persistence:
      enabled: true
      size: 10Gi

# Realm configuration for DemoJam
realm:
  name: "demojam"
  displayName: "DemoJam AI Assistant"
  
  # OAuth2 clients
  clients:
    backstage:
      clientId: "backstage"
      secret: "backstage-client-secret"
    aiAssistant:
      clientId: "ai-assistant"  
      secret: "ai-assistant-client-secret"
      
  # Default users
  users:
    admin:
      username: "demojam-admin"
      password: "demojam-admin-123"
      email: "admin@company.com"