apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base Helm charts desde repositorio externo
helmCharts:
- name: setup-platform-gitea
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "1.0.0"
  releaseName: gitea
  namespace: gitea
  valuesFile: values-prod.yaml
  
- name: setup-platform-bookstack  
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "1.0.0"
  releaseName: bookstack
  namespace: bookstack-corporate
  valuesFile: values-prod.yaml
  
- name: setup-rh-developer-hub
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "1.0.0"
  releaseName: rhdh
  namespace: backstage
  valuesFile: values-prod.yaml
  
- name: setup-rh-keycloak
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "1.0.1"
  releaseName: rhbk
  namespace: rhbk-operator
  valuesFile: values-prod.yaml
  
- name: setup-app-openshift-ai-asistant
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "2.0.0"
  releaseName: ai-assistant
  namespace: demojam-ai-assistant
  valuesFile: values-prod.yaml

# Customizaciones para producción
commonLabels:
  project: demojam-2026
  environment: production
  managed-by: kustomize

# Patches específicos para producción
patches:
- target:
    kind: Deployment
    labelSelector: "app in (gitea, bookstack, rhdh)"
  patch: |
    - op: replace
      path: /spec/replicas
      value: 2
      
- target:
    kind: Deployment
    name: ai-assistant
  patch: |
    - op: replace
      path: /spec/replicas
      value: 3
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENVIRONMENT
        value: "production"

# Recursos adicionales para producción
resources:
- network-policies.yaml
- resource-quotas.yaml