apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-assistant.fullname" . }}
  namespace: {{ .Values.namespace | default "demojam-ai-assistant" }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ai-assistant.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: QUARKUS_PROFILE
            value: {{ .Values.environment | default "prod" }}
          - name: OPENSHIFT_AI_ENDPOINT
            value: {{ .Values.config.openshift.ai.endpoint }}
          - name: OPENSHIFT_AI_MODEL
            value: {{ .Values.config.openshift.ai.model }}
          - name: BOOKSTACK_URL
            value: {{ .Values.config.external.bookstack.url }}
          - name: GITEA_URL
            value: {{ .Values.config.external.gitea.url }}
          - name: KEYCLOAK_URL
            value: {{ .Values.config.external.keycloak.url }}
          - name: DATABASE_URL
            value: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@postgresql:5432/{{ .Values.postgresql.auth.database }}"
          - name: REDIS_URL
            value: "redis://redis:6379"
          {{- if .Values.qdrant.enabled }}
          - name: QDRANT_URL
            value: "http://qdrant:6333"
          {{- end }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}