{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ai-assistant.fullname" . }}
  namespace: {{ .Values.namespace | default "demojam-ai-assistant" }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ai-assistant.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  # Allow database connections
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
    ports:
    - protocol: TCP
      port: 5432
  # Allow Redis connections
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: 6379
  # Allow external API calls (OpenShift AI, etc)
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}