apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-assistant.fullname" . }}
  namespace: {{ .Values.namespace | default "demojam-ai-assistant" }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-assistant.selectorLabels" . | nindent 4 }}