apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demojam-ai-assistant

resources:
  - ../../base

configMapGenerator:
  - name: ai-assistant-prod-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
      - ENABLE_DEBUG=false

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2