apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base: Helm chart AI Assistant
helmCharts:
- name: setup-app-openshift-ai-asistant
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "2.0.0"
  releaseName: ai-assistant
  namespace: demojam-ai-assistant

# Customizaciones específicas para AI Assistant
patches:
- target:
    kind: Deployment
    name: ai-assistant
  patch: |
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: MCP_TOOLS_CONFIG
        valueFrom:
          configMapKeyRef:
            name: ai-assistant-mcp-config
            key: tools.json

# Recursos adicionales específicos AI Assistant
resources:
- mcp-tools-configmap.yaml
- agent-configurations.yaml
- openshift-ai-connection.yaml

# Labels específicos
commonLabels:
  component: ai-assistant