# Valores base para Red Hat Developer Hub
global:
  clusterRouterBase: apps.your-cluster.com
  
backstage:
  enabled: true
  
  replicas: 1
  
  image:
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1000m

  postgresql:
    enabled: true
    auth:
      database: backstage
      username: backstage
    primary:
      persistence:
        enabled: true
        size: 8Gi

  plugins:
    - name: kubernetes
      enabled: true
    - name: techdocs
      enabled: true
    - name: catalog
      enabled: true
    - name: scaffolder
      enabled: true

  auth:
    providers:
      - type: oauth2
        providerId: keycloak
        
  cors:
    origin: "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS