apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhbk-operator

resources:
  - ../../base

configMapGenerator:
  - name: keycloak-prod-config
    behavior: merge
    literals:
      - KC_LOG_LEVEL=INFO
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_CACHE=ispn
      - KC_CACHE_STACK=kubernetes

patches:
  - target:
      kind: Keycloak
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/instances
        value: 2
      - op: add
        path: /metadata/labels/environment
        value: production