apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - ../../base

configMapGenerator:
  - name: rhdh-prod-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn
      - ENABLE_METRICS=true
      - ENABLE_TRACING=true

patches:
  - target:
      kind: Deployment
      name: rh-developer-hub
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /metadata/labels/environment
        value: production

patchesStrategicMerge:
  - resources-patch.yaml