apiVersion: apps/v1
kind: Deployment
metadata:
  name: rh-developer-hub
spec:
  template:
    spec:
      containers:
      - name: backstage
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 2000m