replicaCount: 1

image:
  repository: gitea/gitea
  tag: "1.21.0"
  pullPolicy: IfNotPresent

config:
  domain: "gitea.apps.cluster.company.com"

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi