apiVersion: v1
kind: Secret
metadata:
  name: bookstack-secrets
  namespace: {{ .Values.namespace | default "bookstack-corporate" }}
type: Opaque
data:
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc }}
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstack-config
  namespace: {{ .Values.namespace | default "bookstack-corporate" }}
data:
  APP_URL: {{ .Values.config.appUrl }}
  APP_KEY: {{ .Values.config.appKey }}
  DB_HOST: {{ .Values.mariadb.host | default "bookstack-mariadb" }}
  DB_PORT: "3306"
  DB_DATABASE: {{ .Values.mariadb.auth.database }}
  DB_USER: {{ .Values.mariadb.auth.username }}
  TZ: {{ .Values.config.timezone | default "America/Lima" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: {{ .Values.namespace | default "bookstack-corporate" }}
  labels:
    app: bookstack
    component: application
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
        component: application
    spec:
      containers:
      - name: bookstack
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: bookstack-config
              key: TZ
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: bookstack-config
              key: APP_URL
        - name: APP_KEY
          valueFrom:
            configMapKeyRef:
              name: bookstack-config
              key: APP_KEY
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bookstack-config
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: bookstack-config
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: bookstack-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: mariadb-password
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: bookstack-storage
          mountPath: /config
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /login
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /login
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: bookstack-storage
        persistentVolumeClaim:
          claimName: bookstack-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: bookstack-service
  namespace: {{ .Values.namespace | default "bookstack-corporate" }}
  labels:
    app: bookstack
spec:
  selector:
    app: bookstack
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bookstack-route
  namespace: {{ .Values.namespace | default "bookstack-corporate" }}
  labels:
    app: bookstack
spec:
  host: {{ .Values.config.domain }}
  to:
    kind: Service
    name: bookstack-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect