apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-instances
  namespace: openshift-gitops
  labels:
    app: keycloak-instances
    project: demojam-2026
    tier: infrastructure
    component: identity-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: demojam
  sources:
  - repoURL: https://jeanlopezxyz.github.io/helm-charts
    targetRevision: 1.0.4
    chart: setup-rh-operator-keycloak
  - repoURL: https://github.com/jeanlopezxyz/demojam-2026
    targetRevision: main
    path: gitops/projects/keycloak
    ref: values
  helm:
    valueFiles:
    - $values/values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators-redhat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m