apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demojam-infrastructure
  namespace: openshift-gitops
  labels:
    app: infrastructure
    project: demojam-2026
    tier: infrastructure
spec:
  project: demojam
  source:
    repoURL: https://github.com/team/demojam-ai-assistant
    targetRevision: HEAD
    path: gitops/apps/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m