apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demojam-infrastructure
  namespace: openshift-gitops
  labels:
    app: infrastructure
    project: demojam-2026
    tier: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: demojam
  source:
    repoURL: https://github.com/jeanlopezxyz/demojam-2026
    targetRevision: main
    path: gitops/projects/infrastructure
    directory:
      include: "*/application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m