site_name: User Service Documentation
site_description: Authentication and user management microservice

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: material
  palette:
    primary: blue

plugins:
  - techdocs-core