apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "backstage" }}
  labels:
    app: rhdh
    component: infrastructure
    project: demojam-2026
  annotations:
    description: "Red Hat Developer Hub namespace"
    openshift.io/display-name: "Red Hat Developer Hub"