# Valores base para Red Hat Build of Keycloak
# Operator installed separately via operators-app
helpers:
  operator:
    enabled: false  # Disabled - operator installed separately
  statusChecker:
    enabled: false  # Disabled for now

operator:
  defaultNamespace: "rhbk-operator"

keycloak:
  instances: 1
  
  # Configuración de la base de datos
  database:
    vendor: postgres
    host: keycloak-postgresql
    port: 5432
    database: keycloak
    username: keycloak
    
  # Configuración HTTP/TLS
  http:
    tlsSecret: keycloak-tls
    
  # Configuración de hostname
  hostname:
    hostname: keycloak.apps.your-cluster.com
    admin: keycloak-admin.apps.your-cluster.com
    strict: false
    
  # Configuración de recursos
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2000m

  # Configuración adicional de Keycloak
  config:
    # Configuración de logging
    KC_LOG_LEVEL: INFO
    KC_DB: postgres
    KC_HEALTH_ENABLED: "true"
    KC_METRICS_ENABLED: "true"
    # Configuración de proxy para producción
    KC_PROXY: edge
    KC_HOSTNAME_STRICT_HTTPS: "true"
    # Configuración de cache
    KC_CACHE: ispn
    KC_CACHE_STACK: kubernetes

postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
    database: keycloak
    username: keycloak
  primary:
    persistence:
      enabled: true
      size: 10Gi
      
realms:
  - name: demojam
    displayName: "DemoJam 2026"
    enabled: true
    loginTheme: keycloak
    
clients:
  - clientId: backstage
    name: "Backstage"
    protocol: openid-connect
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    rootUrl: https://backstage.apps.your-cluster.com
    baseUrl: /
    redirectUris:
      - https://backstage.apps.your-cluster.com/*
    webOrigins:
      - https://backstage.apps.your-cluster.com