apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: {{ .Values.namespace | default "gitea" }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
  gitea-admin-password: {{ .Values.gitea.adminPassword | b64enc }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: {{ .Values.namespace | default "gitea" }}
  labels:
    app: gitea
    component: git-server
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
        component: git-server
    spec:
      containers:
      - name: gitea
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: TZ
          value: {{ .Values.config.timezone | default "America/Lima" }}
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "{{ .Values.postgresql.host | default "gitea-postgresql" }}:5432"
        - name: GITEA__database__NAME
          value: {{ .Values.postgresql.auth.database }}
        - name: GITEA__database__USER
          value: {{ .Values.postgresql.auth.username }}
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: postgres-password
        - name: GITEA__server__DOMAIN
          value: {{ .Values.config.domain }}
        - name: GITEA__server__ROOT_URL
          value: {{ .Values.config.rootUrl }}
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 2222
          name: ssh
        volumeMounts:
        - name: gitea-storage
          mountPath: /data
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 200
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: gitea-storage
        persistentVolumeClaim:
          claimName: gitea-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: {{ .Values.namespace | default "gitea" }}
  labels:
    app: gitea
spec:
  selector:
    app: gitea
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  - port: 2222
    targetPort: 2222
    name: ssh
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitea-route
  namespace: {{ .Values.namespace | default "gitea" }}
  labels:
    app: gitea
spec:
  host: {{ .Values.config.domain }}
  to:
    kind: Service
    name: gitea-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect