apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "gitea" }}
  labels:
    app: gitea
    component: infrastructure
    project: demojam-2026
  annotations:
    description: "Gitea Git repository server namespace"
    openshift.io/display-name: "Gitea Corporate"