apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: {{ .Values.namespace | default "gitea" }}
  labels:
    app: gitea
spec:
  selector:
    app: gitea
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  - port: 2222
    targetPort: 2222
    name: ssh
  type: ClusterIP