# Valores de producción para Gitea
namespace:
  create: false  # ArgoCD creates namespace

replicaCount: 1

image:
  repository: gitea/gitea
  tag: "1.21.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

# OpenShift Route
route:
  enabled: true
  host: gitea.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

# Gitea configuration
gitea:
  config:
    server:
      DOMAIN: gitea.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
      ROOT_URL: https://gitea.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
      SSH_DOMAIN: gitea.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
    service:
      DISABLE_REGISTRATION: true
      ENABLE_PUSH_CREATE_USER: false
      ENABLE_PUSH_CREATE_ORG: false
    repository:
      DEFAULT_BRANCH: main
      DISABLE_HTTP_GIT: false

persistence:
  enabled: true
  size: 10Gi
  storageClass: gp3-csi

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi
    storageClass: gp3-csi
  auth:
    database: gitea
    username: gitea

# Security Context for OpenShift
podSecurityContext:
  enabled: true
  fsGroup: null
  runAsUser: null

containerSecurityContext:
  enabled: true
  runAsUser: "auto"
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault