apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demojam
  namespace: openshift-gitops
  labels:
    project: demojam
spec:
  description: Red Hat One 2026 DemoJam - AI Assistant Project
  
  # Source repositories permitidos
  sourceRepos:
  - https://github.com/jeanlopezxyz/demojam-2026
  - https://charts.bitnami.com/bitnami
  - https://codecentric.github.io/helm-charts
  - https://prometheus-community.github.io/helm-charts
  
  # Clusters de destino permitidos
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: demojam-ai-assistant
    server: https://kubernetes.default.svc
  - namespace: backstage
    server: https://kubernetes.default.svc
  - namespace: rhbk-operator
    server: https://kubernetes.default.svc
  - namespace: bookstack-corporate
    server: https://kubernetes.default.svc
  - namespace: gitea
    server: https://kubernetes.default.svc
  - namespace: openshift-pipelines
    server: https://kubernetes.default.svc
    
  # Recursos permitidos
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: argoproj.io
    kind: Application
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: route.openshift.io
    kind: Route
    
  # Recursos denegados (seguridad)
  clusterResourceBlacklist:
  - group: ""
    kind: Secret
  - group: v1
    kind: Secret
    
  # Namespaces permitidos
  namespaceResourceWhitelist:
  - group: ""
    kind: ConfigMap
  - group: ""
    kind: Service
  - group: ""
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: networking.k8s.io
    kind: NetworkPolicy
    
  # Roles para el proyecto
  roles:
  - name: developer
    description: Developer access to DemoJam project
    policies:
    - p, proj:demojam:developer, applications, get, demojam/*, allow
    - p, proj:demojam:developer, applications, sync, demojam/*, allow
    groups:
    - company:demojam-developers
    
  - name: admin
    description: Admin access to DemoJam project
    policies:
    - p, proj:demojam:admin, applications, *, demojam/*, allow
    - p, proj:demojam:admin, repositories, *, *, allow
    groups:
    - company:demojam-admins