apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demojam
  namespace: openshift-gitops
  labels:
    project: demojam
spec:
  description: Red Hat One 2026 DemoJam - AI Assistant Project
  
  # Source repositories permitidos
  sourceRepos:
  - https://github.com/jeanlopezxyz/demojam-2026
  - https://github.com/jeanlopezxyz/helm-charts
  - https://jeanlopezxyz.github.io/helm-charts
  - https://charts.bitnami.com/bitnami
  - https://codecentric.github.io/helm-charts
  - https://prometheus-community.github.io/helm-charts
  
  # Clusters de destino permitidos
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: demojam-ai-assistant
    server: https://kubernetes.default.svc
  - namespace: backstage
    server: https://kubernetes.default.svc
  - namespace: rhbk-operator
    server: https://kubernetes.default.svc
  - namespace: bookstack-corporate
    server: https://kubernetes.default.svc
  - namespace: gitea
    server: https://kubernetes.default.svc
  - namespace: openshift-pipelines
    server: https://kubernetes.default.svc
    
  # Recursos permitidos a nivel cluster
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: argoproj.io
    kind: Application
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: route.openshift.io
    kind: Route
  # Operadores
  - group: operators.coreos.com
    kind: Subscription
  - group: operators.coreos.com
    kind: OperatorGroup
  - group: operators.coreos.com
    kind: ClusterServiceVersion
  # Keycloak CRDs
  - group: keycloak.org
    kind: Keycloak
  - group: keycloak.org
    kind: KeycloakRealm
  - group: keycloak.org
    kind: KeycloakClient
  # Tekton CRDs
  - group: tekton.dev
    kind: Pipeline
  - group: tekton.dev
    kind: Task
  - group: tekton.dev
    kind: PipelineRun
  # Monitoring
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: monitoring.coreos.com
    kind: PrometheusRule
    
  # Recursos denegados a nivel de cluster (seguridad)
  clusterResourceBlacklist:
  - group: ""
    kind: Secret
  - group: v1
    kind: Secret
  # Note: Secrets are allowed at namespace level but not cluster level
    
  # Recursos permitidos a nivel namespace
  namespaceResourceWhitelist:
  - group: ""
    kind: ConfigMap
  - group: ""
    kind: Service
  - group: ""
    kind: ServiceAccount
  - group: ""
    kind: PersistentVolumeClaim
  - group: ""
    kind: Secret
  - group: ""
    kind: Pod
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: ReplicaSet
  - group: apps
    kind: DaemonSet
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  - group: policy
    kind: PodDisruptionBudget
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: networking.k8s.io
    kind: Ingress
  - group: route.openshift.io
    kind: Route
  - group: argoproj.io
    kind: Application
  # Batch jobs para backups
  - group: batch
    kind: Job
  - group: batch
    kind: CronJob
  # Keycloak resources
  - group: keycloak.org
    kind: Keycloak
  - group: keycloak.org
    kind: KeycloakRealm
  - group: keycloak.org
    kind: KeycloakClient
  # Tekton resources
  - group: tekton.dev
    kind: Pipeline
  - group: tekton.dev
    kind: Task
  - group: tekton.dev
    kind: PipelineRun
  - group: tekton.dev
    kind: TaskRun
  # Monitoring resources
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: monitoring.coreos.com
    kind: PrometheusRule
  # Extensions
  - group: extensions
    kind: Deployment
  - group: extensions
    kind: Ingress
    
  # Roles para el proyecto
  roles:
  - name: developer
    description: Developer access to DemoJam project
    policies:
    - p, proj:demojam:developer, applications, get, demojam/*, allow
    - p, proj:demojam:developer, applications, sync, demojam/*, allow
    groups:
    - company:demojam-developers
    
  - name: admin
    description: Admin access to DemoJam project
    policies:
    - p, proj:demojam:admin, applications, *, demojam/*, allow
    - p, proj:demojam:admin, repositories, *, *, allow
    groups:
    - company:demojam-admins