apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-instances
  namespace: openshift-gitops
  labels:
    app: keycloak
    project: demojam-2026
    tier: infrastructure
    component: identity-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: demojam
  source:
    repoURL: https://github.com/jeanlopezxyz/demojam-2026
    targetRevision: main
    path: gitops/values/infrastructure/keycloak
    helm:
      valueFiles:
      - values-production.yaml
      chart: setup-rh-operator-keycloak
      repo: https://jeanlopezxyz.github.io/helm-charts
      version: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: rhbk-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true