# Development Profile - Local CORS Configuration
quarkus:
  http:
    cors:
      ~: true
      origins: 
        - "http://localhost:3000"      # Local React dev server
        - "http://127.0.0.1:3000"      # Alternative localhost
        - "http://0.0.0.0:3000"        # Docker alternative
      methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
      headers: 
        - "*"                          # Allow all headers in development
      credentials: true
      max-age: 3600
      
  # Development logging
  log:
    level: DEBUG
    category:
      "com.redhat.ecommerce.gateway": DEBUG
      "io.quarkus.http.cors": DEBUG   # Debug CORS issues
      
  # Development OIDC (local Keycloak or external)
  oidc:
    auth-server-url: ${KEYCLOAK_URL:http://localhost:8090}/realms/${KEYCLOAK_REALM:ecommerce}
    token:
      verification-strategy: local    # Faster for dev