apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demojam-app-of-apps
  namespace: openshift-gitops
  labels:
    app: demojam-root
    project: demojam-2026
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demojam
  source:
    repoURL: https://github.com/jeanlopezxyz/demojam-2026
    targetRevision: HEAD
    path: gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status