apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: openshift-gitops
  labels:
    app: gitea
    project: demojam
    component: git-repository
spec:
  project: demojam
  source:
    repoURL: https://github.com/jeanlopezxyz/demojam-2026
    targetRevision: HEAD
    path: gitops/kustomize/overlays/prod
    kustomize:
      images:
      - name: gitea/gitea
        newTag: "1.21.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Secret
    jsonPointers:
    - /data