apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-instances
  namespace: openshift-gitops
  labels:
    app: keycloak-instances
    project: demojam-2026
    tier: infrastructure
    component: identity-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: demojam
  source:
    repoURL: https://jeanlopezxyz.github.io/helm-charts
    targetRevision: 1.0.4
    chart: setup-rh-operator-keycloak
    helm:
      valueFiles: []
      values: |
        # Operator installed separately via operators-app
        helpers:
          operator:
            enabled: false
          statusChecker:
            enabled: false

        operator:
          defaultNamespace: "rhbk-operator"

        keycloak:
          instances: 2  # Producción
          
          database:
            vendor: postgres
            host: keycloak-postgresql
            port: 5432
            database: keycloak
            username: keycloak
            
          http:
            tlsSecret: keycloak-tls
            
          hostname:
            hostname: keycloak.apps.your-cluster.com
            admin: keycloak-admin.apps.your-cluster.com
            strict: false
            
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 2000m

          config:
            KC_LOG_LEVEL: INFO
            KC_DB: postgres
            KC_HEALTH_ENABLED: "true"
            KC_METRICS_ENABLED: "true"
            KC_PROXY: edge
            KC_HOSTNAME_STRICT_HTTPS: "true"
            KC_CACHE: ispn
            KC_CACHE_STACK: kubernetes

        postgresql:
          enabled: true
          auth:
            postgresPassword: postgres
            database: keycloak
            username: keycloak
          primary:
            persistence:
              enabled: true
              size: 10Gi
              
        realms:
          - name: demojam
            displayName: "DemoJam 2026"
            enabled: true
            loginTheme: keycloak
            
        clients:
          - clientId: backstage
            name: "Backstage"
            protocol: openid-connect
            publicClient: false
            standardFlowEnabled: true
            directAccessGrantsEnabled: true
            rootUrl: https://backstage.apps.your-cluster.com
            baseUrl: /
            redirectUris:
              - https://backstage.apps.your-cluster.com/*
            webOrigins:
              - https://backstage.apps.your-cluster.com
  destination:
    server: https://kubernetes.default.svc
    namespace: rhbk-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m