apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gitea
  namespace: openshift-gitops
  labels:
    app: gitea
    project: demojam
    component: git-repository
spec:
  project: demojam
  source:
    repoURL: https://github.com/jeanlopezxyz/helm-charts
    targetRevision: HEAD
    path: charts/setup-platform-gitea
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Secret
    jsonPointers:
    - /data