apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gitea
  namespace: openshift-gitops
  labels:
    app: gitea
    project: demojam
    component: git-repository
spec:
  project: demojam
  source:
    repoURL: https://jeanlopezxyz.github.io/helm-charts
    targetRevision: 1.1.0
    chart: setup-platform-gitea
    helm:
      valueFiles: []
      values: |
        replicaCount: 1
        gitea:
          config:
            server:
              DOMAIN: gitea.apps.your-cluster.com
              ROOT_URL: https://gitea.apps.your-cluster.com
            database:
              DB_TYPE: postgres
              HOST: gitea-postgresql:5432
            service:
              DISABLE_REGISTRATION: true
        persistence:
          enabled: true
          size: 10Gi
        postgresql:
          enabled: true
          persistence:
            enabled: true
            size: 8Gi
          auth:
            database: gitea
            username: gitea
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: Secret
    jsonPointers:
    - /data