apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-bookstack
  namespace: openshift-gitops
  labels:
    app: bookstack
    project: demojam-2026
    tier: infrastructure
    component: documentation
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: demojam
  source:
    repoURL: https://jeanlopezxyz.github.io/helm-charts
    targetRevision: 1.0.0
    chart: setup-platform-bookstack
    helm:
      valueFiles: []
      values: |
        replicaCount: 2
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        persistence:
          enabled: true
          size: 5Gi
        env:
          - name: APP_URL
            value: "https://bookstack-corporate.apps.your-cluster.com"
          - name: APP_ENV
            value: "production"
        mariadb:
          enabled: true
          auth:
            database: bookstack
            username: bookstack
          primary:
            persistence:
              enabled: true
              size: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: bookstack-corporate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m