apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rh-keycloak
  namespace: openshift-gitops
  labels:
    app: rhbk
    project: demojam-2026
    tier: infrastructure
    component: identity-management
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: demojam
  source:
    repoURL: https://jeanlopezxyz.github.io/helm-charts
    chart: setup-rh-operator-keycloak
    targetRevision: "1.0.0"
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rhbk-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true