# Valores de producción para Red Hat Build of Keycloak
helpers:
  operator:
    enabled: true
    operators:
      rhbk-operator:
        enabled: true
        syncwave: 0
        namespace:
          name: rhbk-operator
        subscription:
          channel: stable-v26.2
          operatorName: rhbk-operator
          source: redhat-operators
  statusChecker:
    enabled: true
    statusChecks:
      checks:
        rhbk-operator:
          enabled: true
          type: deployment
          namespace: rhbk-operator
          name: rhbk-operator

keycloak:
  # Namespace configuration
  namespace:
    create: true
    name: rhbk-operator

  # Keycloak instance
  instance:
    enabled: true
    name: keycloak
    replicas: 2  # Producción

  # Hostname configuration
  hostname:
    enabled: true
    value: keycloak.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
    strict: false

  # HTTP configuration  
  http:
    httpEnabled: true

  # Update strategy
  update:
    strategy: RecreateOnImageChange

  # Network Policy
  networkPolicy:
    enabled: true

  # Database configuration
  database:
    external: false  # Use internal PostgreSQL
    vendor: postgres

  # Resource configuration
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

  # Admin credentials
  admin:
    password: "admin123"

  # Additional options
  additionalOptions:
    - name: log-level
      value: INFO
    - name: metrics-enabled
      value: "true"
    - name: health-enabled
      value: "true"

  # Realm configuration
  realm:
    enabled: true
    name: default-realm-import
    realmName: demojam
    displayName: "DemoJam 2026"

    users:
      - username: admin
        firstName: Admin
        lastName: User
        email: admin@demojam.com
        credentials:
          - type: password
            value: admin123
            temporary: false
        realmRoles:
          - admin

    clients:
      - clientId: backstage
        name: "Backstage"
        protocol: openid-connect
        publicClient: false
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
        rootUrl: https://backstage.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
        redirectUris:
          - "https://backstage.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com/*"
        webOrigins:
          - "https://backstage.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com"