# Valores de producción para Red Hat Build of Keycloak
helpers:
  operator:
    enabled: true
    operators:
      rhbk-operator:
        enabled: true
        syncwave: 0
        namespace:
          name: openshift-operators-redhat
        subscription:
          channel: stable
          operatorName: rhbk-operator
          source: redhat-operators
  statusChecker:
    enabled: true

operator:
  defaultNamespace: "rhbk-operator"

keycloak:
  # Namespace configuration
  namespace:
    create: true
    name: keycloak

  # Keycloak instance
  instance:
    enabled: true
    name: keycloak
    replicas: 2  # Producción

  # Hostname configuration
  hostname:
    enabled: true
    value: keycloak.apps.your-cluster.com
    strict: false

  # HTTP configuration  
  http:
    tlsSecret: keycloak-tls

  # Update strategy
  update:
    strategy: RecreateOnImageChange

  # Network Policy
  networkPolicy:
    enabled: true

  # Database configuration
  database:
    external: true
    vendor: postgres
    host: keycloak-postgresql
    port: 5432
    name: keycloak
    credentialsSecret: keycloak-db-secret

  # Resources
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2000m

postgresql:
  enabled: true
  auth:
    postgresPassword: postgres
    database: keycloak
    username: keycloak
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ocs-external-storagecluster-ceph-rbd
      
realms:
  - name: demojam
    displayName: "DemoJam 2026"
    enabled: true
    loginTheme: keycloak
    
clients:
  - clientId: backstage
    name: "Backstage"
    protocol: openid-connect
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    rootUrl: https://backstage.apps.your-cluster.com
    baseUrl: /
    redirectUris:
      - https://backstage.apps.your-cluster.com/*
    webOrigins:
      - https://backstage.apps.your-cluster.com