# Valores de producción para AI Assistant
replicaCount: 2

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

route:
  enabled: true
  host: ai-assistant.apps.cluster-tzfv6.tzfv6.sandbox1862.opentlc.com
  tls:
    enabled: true