apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base: Helm chart sin modificaciones
helmCharts:
- name: setup-platform-gitea
  repo: https://github.com/jeanlopezxyz/helm-charts
  version: "1.0.0"
  releaseName: gitea
  namespace: gitea

# Customizaciones específicas para este componente
patches:
- target:
    kind: Deployment
    name: gitea
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: GITEA__server__DOMAIN
        value: "gitea.apps.cluster-7n8gb.dynamic.redhatworkshops.io"

# Recursos adicionales solo para Gitea
resources:
- gitea-backup-cronjob.yaml
- gitea-networkpolicy.yaml

# Labels específicos
commonLabels:
  component: gitea