apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-backup
  namespace: gitea
  labels:
    app: gitea
    component: backup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:15
            command:
            - /bin/bash
            - -c
            - |
              pg_dump -h postgresql -U gitea gitea > /backup/gitea-$(date +%Y%m%d).sql
              echo "Backup completed: gitea-$(date +%Y%m%d).sql"
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-postgresql-secret
                  key: password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: gitea-backup-pvc
          restartPolicy: OnFailure

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-backup-pvc
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi