apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base desde el directorio base
resources:
- ../../base

# Customizaciones para desarrollo
namePrefix: dev-

# Labels adicionales para dev
commonLabels:
  environment: development
  
# Patches específicos para desarrollo
patches:
- target:
    kind: Deployment
    name: .*gitea.*
  patch: |
    - op: replace
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: GITEA_DEBUG
        value: "true"

- target:
    kind: Deployment  
    name: .*ai-assistant.*
  patch: |
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"

# ConfigMaps específicos para dev
configMapGenerator:
- name: dev-config
  literals:
  - LOG_LEVEL=DEBUG
  - ENVIRONMENT=development
  - DEBUG_MODE=true