# Valores personalizados para Bookstack
# Estos valores sobrescriben los valores por defecto del chart

# Ejemplo de personalizaciones:
replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Configuración de persistencia
persistence:
  enabled: true
  size: 5Gi
  
# Variables de entorno personalizadas
env:
  - name: APP_URL
    value: "https://bookstack-corporate.apps.your-cluster.com"
  - name: APP_DEBUG
    value: "false"

# Configuración de MariaDB
mariadb:
  enabled: true
  auth:
    database: bookstack
    username: bookstack
  primary:
    persistence:
      enabled: true
      size: 8Gi