apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-corporate

resources:
  - ../../base

# Valores específicos para producción
configMapGenerator:
  - name: bookstack-prod-config
    literals:
      - APP_ENV=production
      - APP_DEBUG=false
      - SESSION_SECURE_COOKIE=true
      - BACKUP_RETENTION_DAYS=30

# Patches específicos para producción
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: production
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi