apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-bookstack
spec:
  template:
    spec:
      containers:
      - name: bookstack
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi